let arry = [
    "Icing pudding danish jelly-o pastry sweet roll lemon drops lollipop pie. Bonbon tart sweet donut pastry jelly. Tart ice cream chupa chups cake marzipan cookie. Pie wafer topping marzipan liquorice croissant tiramisu. Jelly-o sesame snaps bear claw tootsie roll shortbread gummies sweet jujubes. Cupcake muffin powder bear claw shortbread brownie. Cotton candy cotton candy marzipan gummi bears cupcake wafer. Biscuit macaroon caramels chocolate bar topping cake jelly beans wafer. Icing ice cream gummies jujubes marshmallow chocolate lemon drops chupa chups. Cheesecake oat cake toffee cheesecake donut macaroon. Gummies tiramisu apple pie pastry sweet roll biscuit tart dragée cotton candy. Oat cake marshmallow shortbread halvah caramels cheesecake bear claw marzipan fruitcake.",
    "Gummi bears bear claw shortbread candy canes jujubes danish jelly sweet roll. Candy canes muffin chocolate cake lollipop ice cream powder jujubes cake ice cream. Bonbon liquorice carrot cake pudding lollipop topping brownie chocolate. Donut dragée pie danish muffin chocolate cake wafer. Toffee sugar plum chocolate bar danish gummi bears gummies cake. Dessert pie toffee biscuit chupa chups sweet jujubes. Cookie lemon drops jelly-o cotton candy icing. Jujubes cookie marshmallow gingerbread apple pie oat cake icing powder sugar plum. Powder marshmallow oat cake candy topping brownie sweet jelly beans cupcake. Ice cream jelly-o pastry candy canes gingerbread wafer soufflé sesame snaps. Soufflé liquorice apple pie soufflé tootsie roll. Marshmallow pudding pudding cheesecake dessert liquorice caramels.", 
    "opping cake tootsie roll icing gummies. Halvah sweet sesame snaps toffee wafer danish gingerbread donut topping. Jelly-o marshmallow cookie jelly beans brownie tart wafer. Gingerbread pastry gingerbread tootsie roll chocolate bar. Jujubes tiramisu carrot cake topping croissant shortbread donut chocolate cake. Bear claw wafer chocolate cake donut dragée pie muffin. Sesame snaps jelly icing shortbread wafer sweet roll tiramisu pie. Oat cake marshmallow jelly beans gummi bears icing macaroon liquorice cheesecake. Chocolate cake chupa chups sweet roll liquorice cookie carrot cake pastry dessert. Muffin bonbon jelly caramels chocolate cake lollipop sesame snaps jelly-o. Cake jelly muffin candy icing. Sugar plum tiramisu jelly toffee oat cake chocolate cake halvah jelly beans. Carrot cake pie wafer cotton candy candy fruitcake. Gingerbread cake pastry shortbread pastry lollipop halvah.",
    "Biscuit sugar plum dessert liquorice sugar plum sweet roll. Biscuit candy croissant topping fruitcake dessert pastry gummi bears. Croissant sugar plum croissant macaroon dessert croissant cake gingerbread pastry. Chocolate bar dragée dessert liquorice donut cookie ice cream cotton candy. Shortbread chupa chups tootsie roll cake ice cream. Sugar plum pastry gummies toffee apple pie muffin carrot cake. Dessert marzipan toffee candy wafer sesame snaps sesame snaps. Cotton candy candy cupcake soufflé pudding croissant sweet liquorice halvah. Muffin tart biscuit chupa chups dessert chupa chups. Cookie jelly-o shortbread tootsie roll chocolate jujubes sesame snaps chocolate bar. Carrot cake pudding caramels dessert croissant chocolate dessert bear claw tart. Soufflé lemon drops wafer marshmallow jelly cupcake tiramisu liquorice. Jujubes oat cake donut shortbread topping lollipop cake. Toffee marshmallow bonbon icing tootsie roll jelly beans.",
    "Gingerbread gingerbread tootsie roll jelly lollipop jelly-o caramels. Shortbread marzipan oat cake tootsie roll ice cream chocolate cake. Brownie biscuit oat cake lemon drops lemon drops fruitcake. Icing powder oat cake sweet danish cake. Cake bear claw macaroon croissant pie marshmallow apple pie. Sesame snaps gummi bears oat cake gingerbread gingerbread bonbon muffin lollipop croissant. Oat cake jelly beans wafer dessert lemon drops pudding chocolate. Gummies pudding liquorice cookie donut. Sesame snaps ice cream cake marshmallow candy sesame snaps chocolate cheesecake. Brownie marzipan pudding caramels cheesecake. Bonbon apple pie sweet muffin donut macaroon. Marzipan caramels fruitcake gummies chocolate apple pie dragée. Topping liquorice wafer cupcake ice cream soufflé caramels. Powder topping fruitcake muffin sweet roll fruitcake jelly jelly lemon drops.",
    "Pudding gingerbread ice cream tart sugar plum cake marshmallow. Sugar plum fruitcake caramels tiramisu dragée gummies chocolate. Cotton candy carrot cake lemon drops jujubes pudding marshmallow powder. Shortbread tiramisu gummies chocolate bar macaroon powder. Croissant dragée pie gummies cake carrot cake marshmallow apple pie. Ice cream cake lollipop candy canes jelly candy. Croissant muffin dessert pie fruitcake soufflé gummies. Topping gummi bears oat cake danish marshmallow lemon drops icing toffee. Chocolate sugar plum shortbread chocolate tart bonbon dragée. Danish candy wafer brownie halvah. Chupa chups croissant sugar plum lollipop marshmallow jelly-o gummies soufflé. Jelly chupa chups powder danish dessert sweet roll. Sweet roll topping oat cake ice cream caramels apple pie icing chupa chups.",

    "Liquorice brownie cake oat cake jelly beans pie cake donut. Ice cream carrot cake cake lemon drops cupcake fruitcake icing. Gummies cake jelly brownie halvah tart sugar plum cotton candy ice cream. Jelly donut sesame snaps brownie jelly marshmallow. Cheesecake cookie apple pie lemon drops candy brownie. Chocolate cotton candy liquorice pastry cotton candy cake apple pie chocolate cake. Powder pie tootsie roll marshmallow jelly. Donut marshmallow jelly jelly-o jelly-o sesame snaps pie halvah. Sweet roll sweet marzipan candy cupcake muffin. Pie powder halvah fruitcake cake shortbread. Sweet liquorice topping candy croissant pie ice cream chocolate bar biscuit. Donut topping cake chocolate cake tart shortbread.", 
    "Gummi bears sesame snaps cheesecake candy shortbread jelly-o. Icing bear claw icing jelly sugar plum gingerbread icing. Chupa chups chocolate bar jelly-o cookie cake candy. Dragée marshmallow cookie tiramisu tiramisu chocolate cake dessert. Dessert biscuit tart tootsie roll halvah cake. Jujubes fruitcake caramels gummies cookie croissant liquorice danish. Sweet roll muffin cake lemon drops jelly-o chocolate cake dessert. Candy chocolate bar powder fruitcake lemon drops fruitcake powder. Chupa chups cake icing cotton candy muffin pudding carrot cake. Icing soufflé cheesecake jujubes cupcake cake tart. Brownie candy marshmallow candy chocolate cake powder. Marzipan cake biscuit marshmallow oat cake oat cake pie.",
    "Candy muffin halvah jelly icing liquorice. Fruitcake candy canes jelly-o icing oat cake. Shortbread sweet roll croissant soufflé bonbon. Jelly beans gummi bears gingerbread shortbread tootsie roll brownie tart sweet. Cake gummi bears lollipop carrot cake chocolate. Sweet tiramisu oat cake jelly beans cake macaroon danish chocolate. Sweet roll candy canes sweet roll oat cake dragée candy canes. Cake donut marzipan chocolate cake sugar plum bonbon sugar plum. Candy canes bear claw jelly lemon drops cupcake chupa chups sugar plum. Sweet roll jujubes cheesecake carrot cake chocolate cake macaroon bear claw jelly. Pie tart wafer jelly beans lemon drops cheesecake cupcake. Cheesecake cake powder chocolate cake chocolate sweet roll caramels donut chocolate bar."
]

var s = document.querySelector("#form")

let y = document.querySelector("#amount")

var i = document.querySelector("#result")


s.addEventListener("click" , function (e) {
    e.preventDefault()

    let x = parseInt(y.value)
   
    let random = Math.floor(Math.random() * arry.length )

    if (x <= 0 || x > 9) {
        i.innerHTML = `<p>${arry[random]} </p>`
    }else{
        let ami = arry.slice(0 , x)
        let sec = ami.map(function (paltu) {
            return `<p>${paltu} </p>`
        }
)
         
        i.innerHTML = sec;
    }
})